apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mern-api
    spec:
      containers:
        - name: mern-api
          image: amiralamti/api
          imagePullPolicy: Always
          ports:
            - containerPort: 3080
              name: nodejs-port
              
  selector:
    matchLabels:
      app: mern-api
      
---
apiVersion: v1
kind: Service
metadata:
  name: mern-api
spec:
  ports:
    - port: 3080
      protocol: TCP
  selector:
    app: mern-api
  type: ClusterIP
  
  
  
