apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongo-db
      image: mongo:4.0.4
      ports:
        - containerPort: 27017
          name: mongodb-port
          
---       
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongo-db
  type: ClusterIP
  
  
